<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>SigningClient</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Gnap.HttpMessageSignatures\Gnap.HttpMessageSignatures.csproj" />
  </ItemGroup>

</Project>
